### ISSUE TITLE
Devolución primer entrega 2020

### ISSUE THREAD

**Issue by nicolasfanin** [AguPereyra/IntegradorMoviles#4]
Esta bien planteada la arquitectura de la app, el código esta ordenado, prolijo y 100% en inglés! Bien por eso!

- En tu navegación, si vuelvo hacía atrás desde el home, vuelvo al login. Si bien el login no esta implementado como tal, desde la navegación se podría evitar volver hacia atrás en una pantalla.

- Tal vez, yo llamaría al paquete "controller" como "ui" o "view" y el controller lo tomaría para implementar managers, o clases que manejen lógica de negocio.

- Excelente que uses Kotlin!

Aspectos considerados:

[Si algún item no esta chequeado, no quiere decir que no se considere al menos una parte en la nota.]

- [x] Login
- [x] Registro / Perfil
- [x] Settings
- [x] Enviar correo
- [x] Pantalla inicial
- [x] Uso de Fragments
- [x] Activities y Navegación
- [x] Recycler View
- [x] Uso de Layouts
- [x] Uso de Resources
- [x] Uso de Drawables
- [x] Uso de Strings
- [x] Prolijidad del código
- [x] Prolijidad de la Interfaz.

**Comment by pereyraagustin** [comment]
Perfecto profe, muchas gracias por la devolución. Voy a realizar las correcciones para lo del login y cambiar el nombre de los paquetes entonces.
