### ISSUE TITLE
Devolución segunda entrega

### ISSUE THREAD

**Issue by nicolasfanin** [AguPereyra/IntegradorMoviles#7]
Agustin, te dejo devolución segunda entrega.

- Creo que hay un mejor uso de Kotlin.
- La clase User puede ser declarada como "data class".
- Respecto a este TODO en `UserAccountModifyPasswordFragment.kt `
```
// TODO: Ask if there is a better way to do this
        listener.setActionBarTitle(getString(R.string.user_account_passwd_title))
        listener.setActionBarHomeButtonAsUp()
```
Se suele hacer en un BaseFragment entonces todos tus fragments heredan de BaseFragment, y BaseFragment hace todas las funcionalidades base. Asi como tu base activity.
- Excelente uso de corutinas y LiveData.
- Muy buenas mejoras en la arquitectura de la app.
- Si te interesa mejorar tus UI, podes usar algo llamado viewBinding que para Kotlin y la arquitectura planteada va muy bien.

Aspectos considerados:
[Si algún ítem no esta chequeado, no quiere decir que no se considere al menos una parte en la nota.]

- [x] Entendimiento / implementación de los temas
- [x] Pantalla de Configuración
- [x] Dialogos / Notificaciones
- [x] AsyncTask / Procesamiento
- [x] Gestion del usuario (login / logout / regisro)
- [x] Home con peliculas. Info Real
- [x] Persistencia Shared Preferences / Files
- [x] Persistencia Base de Datos
- [x] Networking Conexión
- [x] Netowrking Procesamiento
- [x] Detalle de producto (pelicula)
- [x] Correcciones de la primera a la segunda entrega
- [x] Legibilidad y Prolijidad del código
- [x] Extras

**Comment by pereyraagustin** [comment]
Perfecto profe, gracias por la devolución. Voy a ver de implementar:

- ViewBinding
- Data class en la clase "User"
- BaseFragment

Una duda:

- Cuando dice que cree que hay un mejor uso de Kotlin, ¿Se refiere a que hay partes en las que podría mejorar mi implementación en Kotlin? ¿O que he mejorado mi implementación con respecto a la primera entrega?
